# SPDX-FileCopyrightText: Nicholas (github.com/nicholascathedu)
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["preview.jpg", "showcase.jpg", "presets.jpg", "README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Nicholas (github.com/nicholascathedu)"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["presets/*.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Nicholas (github.com/nicholascathedu)"
SPDX-License-Identifier = "CC0-1.0"
